title:              Blogs by Jesna Mathews
tagline:            
description:        Content focussed Blogs
url:                http://YourName.github.io

author:
  name:             Jesna Mathews
  url:              https://twitter.com/mathews_jesna
  email:            jess4.in@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
